# Generated by Django 3.2.6 on 2021-08-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
            ],
        ),
    ]
