# Generated by Django 3.2.6 on 2021-08-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210827_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestemp',
            name='per_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
