# Generated by Django 3.2.6 on 2021-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_salestemp_per_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cash', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('inventory_value', models.IntegerField()),
                ('total_sales', models.IntegerField()),
                ('total_purchases', models.IntegerField()),
            ],
        ),
    ]
